export interface Service {
  id: number;
  name: string;
  category: string;
  price: number;
  description: string;
  features: string[];
  deliveryTime: string;
  icon: string;
}

export interface EnterprisePlan {
  id: number;
  name: string;
  price: string;
  period: string;
  tagline: string;
  features: string[];
  highlighted: boolean;
  color: string;
}

export const SERVICES_DATA: Service[] = [
  // ── ANALYTICS (5) ──────────────────────────────────────────
  {
    id: 1,
    name: "Google Analytics 4 Full Setup",
    category: "Analytics",
    price: 9999,
    description:
      "Complete GA4 implementation with custom events, goals, and advanced eCommerce tracking.",
    features: [
      "Full GA4 property setup with 50+ custom events configured",
      "Enhanced measurement for scroll depth, video, file downloads",
      "Conversion goal tracking for leads, purchases & micro-conversions",
      "Cross-domain tracking setup for multi-site funnels",
      "Data layer implementation for dynamic content tracking",
      "30-day post-setup monitoring and bug fixes included",
    ],
    deliveryTime: "5–7 days",
    icon: "📊",
  },
  {
    id: 2,
    name: "Custom KPI Dashboard Build",
    category: "Analytics",
    price: 17499,
    description:
      "Real-time business intelligence dashboard connecting all your marketing and sales data sources.",
    features: [
      "Looker Studio / Data Studio dashboard with 20+ KPI widgets",
      "Live data connectors: GA4, Google Ads, Meta Ads, CRM, Sheets",
      "Automated daily/weekly email reports to stakeholders",
      "Revenue attribution modeling with multi-touch analysis",
      "Drill-down filters by channel, date range, and segment",
    ],
    deliveryTime: "5–7 days",
    icon: "📈",
  },
  {
    id: 3,
    name: "Conversion Rate Tracking Setup",
    category: "Analytics",
    price: 12499,
    description:
      "End-to-end conversion tracking across all paid and organic channels with attribution.",
    features: [
      "Google Tag Manager container setup with 30+ tags and triggers",
      "Facebook Pixel + CAPI (server-side) integration for iOS tracking",
      "LinkedIn Insight Tag and Twitter Pixel configuration",
      "Phone call tracking integration (CallRail or similar)",
      "Funnel visualization reports showing drop-off at each stage",
      "Monthly conversion audit report with optimization recommendations",
    ],
    deliveryTime: "5–7 days",
    icon: "🎯",
  },
  {
    id: 4,
    name: "Heatmap & User Behaviour Analysis",
    category: "Analytics",
    price: 14999,
    description:
      "Hotjar/Microsoft Clarity implementation to reveal exactly how users interact with your site.",
    features: [
      "Hotjar or Microsoft Clarity full installation and configuration",
      "Click maps, scroll maps, and movement heatmaps on all key pages",
      "Session recording setup with 3-month data retention",
      "Rage-click and frustration signal analysis report",
      "A/B testing hypothesis report based on behaviour data",
    ],
    deliveryTime: "3–5 days",
    icon: "🔥",
  },
  {
    id: 5,
    name: "Marketing Attribution Modeling",
    category: "Analytics",
    price: 29999,
    description:
      "Advanced multi-touch attribution to understand which channels truly drive your revenue.",
    features: [
      "Custom attribution model (linear, time-decay, data-driven) setup",
      "Offline and online touchpoint unification via CRM data sync",
      "ROAS calculation per channel with blended cost analysis",
      "Assisted conversion reporting to identify dark-funnel contributors",
      "Monthly attribution audit and budget reallocation recommendations",
      "Executive-level attribution summary deck each quarter",
    ],
    deliveryTime: "6–7 days",
    icon: "🔗",
  },

  // ── AUTOMATION & AI (4) ────────────────────────────────────
  {
    id: 6,
    name: "CRM Workflow Automation",
    category: "Automation & AI",
    price: 24999,
    description:
      "Build intelligent CRM automations that qualify, route, and nurture leads without manual work.",
    features: [
      "Complete CRM audit and workflow architecture design",
      "Lead scoring model with 15+ behavioral and demographic triggers",
      "Automated deal-stage progression and task creation rules",
      "Sales rep notification system via email, SMS & WhatsApp",
      "Lost deal re-engagement sequence with 7-touch automation",
    ],
    deliveryTime: "5–7 days",
    icon: "⚙️",
  },
  {
    id: 7,
    name: "AI Chatbot Development",
    category: "Automation & AI",
    price: 49999,
    description:
      "Deploy a GPT-powered chatbot that qualifies leads, books appointments, and answers FAQs 24/7.",
    features: [
      "Custom AI chatbot trained on your products, FAQs, and tone of voice",
      "Live chat handoff logic to human agents when needed",
      "Lead qualification flow capturing name, email, phone & intent",
      "Calendar booking integration for automatic appointment scheduling",
      "WhatsApp, website widget & Instagram DM deployment",
      "Monthly conversation analytics and bot performance report",
    ],
    deliveryTime: "6–7 days",
    icon: "🤖",
  },
  {
    id: 8,
    name: "Email Sequence Automation",
    category: "Automation & AI",
    price: 39999,
    description:
      "AI-crafted email sequences that nurture prospects from cold to closed on autopilot.",
    features: [
      "10-email welcome and nurture sequence with A/B subject line testing",
      "Behavior-triggered branching sequences based on opens and clicks",
      "Cart abandonment and re-engagement flows for eCommerce",
      "CRM integration to pause sequences when deals move stages",
      "Monthly deliverability audit and list hygiene cleaning",
    ],
    deliveryTime: "5–7 days",
    icon: "📧",
  },
  {
    id: 9,
    name: "Sales Funnel Automation",
    category: "Automation & AI",
    price: 1,
    description:
      "End-to-end automated sales funnel from ad click to closed deal with zero manual touches.",
    features: [
      "Full funnel mapping: awareness → interest → decision → action",
      "Landing page + lead magnet + thank-you page automation setup",
      "Instant lead notification + automated first-touch in under 5 minutes",
      "7-day automated follow-up sequence via email and WhatsApp",
      "Payment gateway integration for frictionless checkout",
      "Real-time funnel performance dashboard with conversion rates",
    ],
    deliveryTime: "6–7 days",
    icon: "🚀",
  },

  // ── BUSINESS & AGENCY (16) ────────────────────────────────
  {
    id: 10,
    name: "White-Label Agency Setup",
    category: "Business & Agency",
    price: 74999,
    description:
      "Launch your own white-label digital agency under your brand with full backend systems.",
    features: [
      "Branded client portal with custom domain and your logo",
      "White-label reporting dashboard for up to 20 clients",
      "Service packaging and pricing strategy consultation",
      "Client onboarding workflow and SOP documentation",
      "White-label proposal templates and contract agreements",
      "30-day launch support and staff training included",
    ],
    deliveryTime: "6–7 days",
    icon: "🏢",
  },
  {
    id: 11,
    name: "Business Strategy Consulting",
    category: "Business & Agency",
    price: 49999,
    description:
      "6-hour deep-dive strategy session to build a data-backed 12-month revenue roadmap.",
    features: [
      "Full business audit: revenue model, costs, margins, and growth levers",
      "Competitor and market positioning analysis",
      "12-month revenue target setting with quarterly milestones",
      "Go-to-market strategy for new products or services",
      "Written strategy report (30+ pages) with priority action plan",
    ],
    deliveryTime: "5–7 days",
    icon: "🗺️",
  },
  {
    id: 12,
    name: "Brand Identity Package",
    category: "Business & Agency",
    price: 39999,
    description:
      "Complete brand identity system from logo to brand guidelines that commands authority.",
    features: [
      "Primary logo + 3 variations (horizontal, stacked, icon-only)",
      "Full color palette, typography system, and icon library",
      "Brand voice and messaging framework document",
      "Business card, letterhead, and email signature designs",
      "Social media profile image and cover templates",
      "Brand guidelines PDF (25+ pages) for consistent usage",
    ],
    deliveryTime: "6–7 days",
    icon: "🎨",
  },
  {
    id: 13,
    name: "Agency CRM Setup",
    category: "Business & Agency",
    price: 29999,
    description:
      "Configure GoHighLevel, HubSpot, or Zoho CRM tailored to agency client management.",
    features: [
      "CRM platform selection and full account configuration",
      "Custom pipelines for sales, onboarding, and delivery",
      "Client communication templates (50+ email and SMS templates)",
      "Automated client health-score alerts and churn prevention triggers",
      "Team permission setup and role-based access control",
    ],
    deliveryTime: "5–7 days",
    icon: "📋",
  },
  {
    id: 14,
    name: "Sales Team Training Program",
    category: "Business & Agency",
    price: 44999,
    description:
      "4-week structured sales training to build a high-performance closer team from scratch.",
    features: [
      "4x live 2-hour virtual training sessions with role-play exercises",
      "Custom sales script and objection handling playbook",
      "CRM usage training and deal tracking best practices",
      "Cold outreach templates: email, LinkedIn, and WhatsApp",
      "Sales KPI dashboard setup and weekly review framework",
      "1-month post-training coaching support via WhatsApp group",
    ],
    deliveryTime: "6–7 days",
    icon: "🏆",
  },
  {
    id: 15,
    name: "Standard Operating Procedures",
    category: "Business & Agency",
    price: 24999,
    description:
      "Documented SOPs for every core business process so your team delivers consistently.",
    features: [
      "Process discovery workshops with your team leads",
      "20 fully documented SOPs with step-by-step instructions",
      "Video walkthroughs for complex multi-step processes",
      "Checklists and templates for each SOP",
      "SOP management system setup (Notion, Trainual, or similar)",
    ],
    deliveryTime: "6–7 days",
    icon: "📝",
  },
  {
    id: 16,
    name: "Business Process Mapping",
    category: "Business & Agency",
    price: 19999,
    description:
      "Visual end-to-end mapping of every business process to find gaps and automation opportunities.",
    features: [
      "As-is process mapping for 10 core business workflows",
      "Bottleneck identification and inefficiency scoring",
      "To-be process redesign with automation opportunities highlighted",
      "Process map documentation in Lucidchart/Miro format",
      "Priority action list for immediate process improvement",
    ],
    deliveryTime: "5–7 days",
    icon: "🔄",
  },
  {
    id: 17,
    name: "Client Onboarding System",
    category: "Business & Agency",
    price: 34999,
    description:
      "Automated, delightful client onboarding that collects info, sets expectations, and wows clients.",
    features: [
      "Branded onboarding portal with custom domain",
      "Automated welcome email sequence (5 emails over 7 days)",
      "Digital intake form builder and document collection system",
      "Project kickoff call scheduling automation",
      "Client access setup for project management and reporting tools",
    ],
    deliveryTime: "5–7 days",
    icon: "🤝",
  },
  {
    id: 18,
    name: "Revenue Dashboard Build",
    category: "Business & Agency",
    price: 22499,
    description:
      "Live revenue command centre showing MRR, ARR, churn, LTV, and pipeline in real time.",
    features: [
      "Custom Looker Studio revenue dashboard with 15+ metrics",
      "CRM + payment gateway data integration",
      "MRR, ARR, churn rate, and LTV calculation automation",
      "Sales pipeline value and velocity tracking",
      "Weekly automated revenue reports emailed to leadership",
    ],
    deliveryTime: "5–7 days",
    icon: "💰",
  },
  {
    id: 19,
    name: "KPI Tracking System",
    category: "Business & Agency",
    price: 17499,
    description:
      "Build a company-wide KPI tracking system so every team knows their targets and progress.",
    features: [
      "Company-wide OKR and KPI framework design",
      "Team-level KPI dashboards for sales, marketing, and operations",
      "Automated weekly KPI report to all team members",
      "Red/amber/green performance alerts via Slack or email",
      "Quarterly KPI review template and facilitation guide",
    ],
    deliveryTime: "5–7 days",
    icon: "📊",
  },
  {
    id: 20,
    name: "Team Productivity Suite",
    category: "Business & Agency",
    price: 27499,
    description:
      "Configure Notion, ClickUp, or Asana as a full team operating system for maximum output.",
    features: [
      "Project management workspace setup and structure design",
      "Team templates for projects, meetings, and task management",
      "Time tracking integration and productivity reporting",
      "Cross-team collaboration workflows and approval processes",
      "Staff training and onboarding guide for the new system",
    ],
    deliveryTime: "5–7 days",
    icon: "⚡",
  },
  {
    id: 21,
    name: "Agency Website Design & Build",
    category: "Business & Agency",
    price: 59999,
    description:
      "High-converting agency website that positions you as the premium choice in your market.",
    features: [
      "Custom design (not templates) with mobile-first approach",
      "10 pages including home, services, case studies, team, and contact",
      "Case study section with before/after results showcase",
      "Lead capture forms with CRM integration",
      "SEO foundation: meta tags, schema markup, site speed optimization",
      "3 rounds of revisions and 30-day post-launch support",
    ],
    deliveryTime: "6–7 days",
    icon: "🌐",
  },
  {
    id: 22,
    name: "Proposal Automation System",
    category: "Business & Agency",
    price: 22499,
    description:
      "Create stunning automated proposals that get signed faster with e-signature integration.",
    features: [
      "Proposal template library (10 service-specific templates)",
      "Pandadoc, Better Proposals, or Proposify setup and configuration",
      "Dynamic pricing and scope customization fields",
      "E-signature integration and automated follow-up reminders",
      "Proposal analytics: open rates, time-on-page, and conversion tracking",
    ],
    deliveryTime: "5–7 days",
    icon: "📄",
  },
  {
    id: 23,
    name: "Contract & Invoice System",
    category: "Business & Agency",
    price: 14999,
    description:
      "Automate contracts, invoicing, and payment collection so cash flow never stalls.",
    features: [
      "Legally reviewed contract templates for 5 service types",
      "Automated invoice generation on project milestone completion",
      "Recurring billing setup for retainer clients",
      "Payment link integration (Razorpay/Stripe) with auto-reminders",
      "Accounts receivable dashboard with overdue alerts",
    ],
    deliveryTime: "5–7 days",
    icon: "📜",
  },
  {
    id: 24,
    name: "Reseller Program Setup",
    category: "Business & Agency",
    price: 39999,
    description:
      "Launch a partner/reseller program to create a network that sells your services for you.",
    features: [
      "Reseller program structure: tiers, commission structure, and rules",
      "Partner portal with deal registration and commission tracking",
      "Co-branded marketing materials and pitch decks",
      "Partner onboarding email sequence and training program",
      "Affiliate tracking software setup and integration",
    ],
    deliveryTime: "6–7 days",
    icon: "🤲",
  },
  {
    id: 25,
    name: "Agency Scale Blueprint",
    category: "Business & Agency",
    price: 149999,
    description:
      "Complete 90-day agency scaling roadmap: hiring, systems, positioning, and revenue growth.",
    features: [
      "Full agency audit: positioning, pricing, capacity, and profitability",
      "Service packaging redesign for higher ticket value",
      "Team structure design and hiring roadmap for 3x capacity",
      "Proprietary framework creation for market differentiation",
      "90-day implementation calendar with weekly action items",
      "Bi-weekly strategy calls for 3 months with founder team",
    ],
    deliveryTime: "7 days",
    icon: "🦁",
  },

  // ── CONTENT MARKETING (7) ─────────────────────────────────
  {
    id: 26,
    name: "Content Strategy & Calendar",
    category: "Content Marketing",
    price: 9999,
    description:
      "Data-driven 90-day content strategy aligned to your SEO and audience growth goals.",
    features: [
      "Audience persona research and content preference mapping",
      "Keyword-clustered topic plan for 90 days (60+ content ideas)",
      "Content distribution strategy across blog, social, and email",
      "Editorial calendar in Notion or Airtable with owner assignments",
      "Content performance KPI framework and monthly review template",
    ],
    deliveryTime: "5–7 days",
    icon: "📅",
  },
  {
    id: 27,
    name: "Blog Writing Package (8 Articles)",
    category: "Content Marketing",
    price: 12499,
    description:
      "8 SEO-optimized long-form articles written by expert writers to rank and convert.",
    features: [
      "8 articles, 1,500–2,500 words each, with original research",
      "Full keyword integration: primary, secondary, and LSI keywords",
      "Custom meta title and description for each article",
      "Internal linking strategy to boost site authority",
      "CTA placement within each article to drive conversions",
    ],
    deliveryTime: "6–7 days",
    icon: "✍️",
  },
  {
    id: 28,
    name: "Lead Magnet Creation",
    category: "Content Marketing",
    price: 14999,
    description:
      "High-value lead magnet (eBook, checklist, or guide) designed to capture qualified leads at scale.",
    features: [
      "Topic ideation based on your audience's biggest pain points",
      "Full written content (15–30 page eBook or comprehensive guide)",
      "Professional layout design in brand colors with custom graphics",
      "Landing page copy for the lead magnet opt-in page",
      "Thank-you page and delivery email sequence",
    ],
    deliveryTime: "5–7 days",
    icon: "🎁",
  },
  {
    id: 29,
    name: "Video Script Writing",
    category: "Content Marketing",
    price: 6499,
    description:
      "Compelling video scripts for YouTube, ads, or explainer videos that hook and convert.",
    features: [
      "5 video scripts (up to 500 words each)",
      "Hook-first structure engineered for maximum watch time",
      "Unique storytelling angle research per script",
      "CTA and offer integration woven naturally into script",
      "Revision rounds until you are 100% satisfied",
    ],
    deliveryTime: "5–7 days",
    icon: "🎬",
  },
  {
    id: 30,
    name: "Case Study Writing Package",
    category: "Content Marketing",
    price: 9999,
    description:
      "3 professionally written case studies that showcase your results and close high-ticket clients.",
    features: [
      "3 case studies following the Problem–Solution–Results framework",
      "Client interview template and data collection guidance",
      "Compelling headline and social proof quote extraction",
      "Designed PDF version for use in proposals and pitches",
      "Short-form social media summary version for each case study",
    ],
    deliveryTime: "5–7 days",
    icon: "🏅",
  },
  {
    id: 31,
    name: "Email Newsletter Setup",
    category: "Content Marketing",
    price: 8999,
    description:
      "Monthly newsletter system that keeps your audience engaged and generates repeat business.",
    features: [
      "Newsletter strategy, format, and editorial framework design",
      "Branded email template design in Mailchimp or Klaviyo",
      "First 4 newsletter editions written and scheduled",
      "Subscriber list segmentation and targeting setup",
      "Open rate and click rate benchmarking with optimisation advice",
    ],
    deliveryTime: "5–7 days",
    icon: "💌",
  },
  {
    id: 32,
    name: "Pillar Content & Topic Cluster Build",
    category: "Content Marketing",
    price: 19999,
    description:
      "Build authoritative topic clusters that dominate search and establish thought leadership.",
    features: [
      "1 pillar page (3,000–5,000 words) on your core service topic",
      "5 supporting cluster articles (1,200–1,800 words each)",
      "Internal linking architecture mapped and implemented",
      "Featured snippet optimization for top 10 questions",
      "Structured data (FAQ schema) added to every page",
    ],
    deliveryTime: "6–7 days",
    icon: "🏛️",
  },

  // ── DIGITAL MARKETING (3) ─────────────────────────────────
  {
    id: 33,
    name: "Digital Marketing Audit",
    category: "Digital Marketing",
    price: 7499,
    description:
      "Comprehensive 360° audit of your entire digital presence with priority fixes and growth opportunities.",
    features: [
      "Website UX, speed, and conversion rate assessment",
      "SEO health check: technical, on-page, and backlink audit",
      "Paid ads account audit with waste identification",
      "Social media profile and engagement analysis",
      "Competitor benchmarking across all channels",
      "Priority action plan with estimated revenue impact per fix",
    ],
    deliveryTime: "5–7 days",
    icon: "🔍",
  },
  {
    id: 34,
    name: "Integrated Digital Marketing Strategy",
    category: "Digital Marketing",
    price: 17499,
    description:
      "12-month omni-channel digital marketing strategy aligned to your revenue and brand goals.",
    features: [
      "Market and audience research with customer journey mapping",
      "Channel mix recommendation: SEO, PPC, social, email, and content",
      "Monthly budget allocation framework by channel",
      "Quarterly campaign calendar with campaign themes and offers",
      "Measurement framework: KPIs, tools, and reporting cadence",
    ],
    deliveryTime: "5–7 days",
    icon: "🌐",
  },
  {
    id: 35,
    name: "Marketing Funnel Build",
    category: "Digital Marketing",
    price: 24999,
    description:
      "Full-stack automated marketing funnel from cold traffic to paying customer in 30 days.",
    features: [
      "Funnel strategy design: stages, offers, and messaging per stage",
      "Landing page and sales page copywriting + design",
      "Opt-in, upsell, and downsell page sequence build",
      "Email and WhatsApp nurture sequence integration",
      "Split testing setup for headline, CTA, and offer variants",
      "Funnel analytics dashboard with real-time conversion data",
    ],
    deliveryTime: "6–7 days",
    icon: "📐",
  },

  // ── EMAIL MARKETING (4) ───────────────────────────────────
  {
    id: 36,
    name: "Email Marketing Platform Setup",
    category: "Email Marketing",
    price: 4999,
    description:
      "Full Mailchimp, Klaviyo, or ActiveCampaign setup including lists, segments, and templates.",
    features: [
      "Platform selection, account setup, and domain authentication (SPF/DKIM)",
      "List import, segmentation, and tag architecture design",
      "Branded email master template in line with your brand identity",
      "Double opt-in and GDPR/CAN-SPAM compliance configuration",
      "Welcome email sequence (3 emails) for new subscribers",
    ],
    deliveryTime: "3–5 days",
    icon: "📬",
  },
  {
    id: 37,
    name: "Cold Email Outreach Campaign",
    category: "Email Marketing",
    price: 12499,
    description:
      "Targeted cold email campaign using Instantly or Lemlist to generate qualified B2B leads.",
    features: [
      "Prospect list building (500 verified leads) in your ICP",
      "5-step cold email sequence with personalisation at scale",
      "Domain warmup, inbox rotation, and deliverability setup",
      "A/B testing of subject lines and opening hooks",
      "Campaign performance report with reply analysis",
    ],
    deliveryTime: "5–7 days",
    icon: "📤",
  },
  {
    id: 38,
    name: "Email Deliverability Optimization",
    category: "Email Marketing",
    price: 7499,
    description:
      "Fix deliverability issues, clean your list, and get back to inbox instead of spam.",
    features: [
      "Full deliverability audit: bounce rates, spam score, and blacklist check",
      "SPF, DKIM, and DMARC configuration and verification",
      "List cleaning and hygiene: remove invalid, unengaged, and spam trap emails",
      "Sender reputation warm-up plan for new or damaged domains",
      "Monthly deliverability monitoring with alerts",
    ],
    deliveryTime: "5–7 days",
    icon: "✅",
  },
  {
    id: 39,
    name: "eCommerce Email Flow Setup",
    category: "Email Marketing",
    price: 14999,
    description:
      "7 essential Klaviyo email flows for eCommerce that recover revenue on autopilot.",
    features: [
      "Welcome series (3 emails), cart abandonment (3 emails), browse abandonment",
      "Post-purchase thank you + review request + upsell sequence",
      "Win-back campaign for lapsed buyers (90+ days inactive)",
      "VIP customer and repeat buyer reward flow",
      "Revenue attribution for each flow with weekly performance alerts",
    ],
    deliveryTime: "5–7 days",
    icon: "🛒",
  },

  // ── ENTERPRISE (3) ────────────────────────────────────────
  {
    id: 40,
    name: "Enterprise CRM Implementation",
    category: "Enterprise",
    price: 149999,
    description:
      "Full Salesforce or HubSpot Enterprise implementation customised to your complex sales process.",
    features: [
      "CRM requirements discovery workshops (3 sessions)",
      "Full platform configuration: objects, fields, layouts, and automation",
      "Custom reports and dashboards for each department head",
      "Data migration from legacy CRM (up to 100k records)",
      "API integration with ERP, billing, and marketing platforms",
      "Team training programme for sales, marketing, and ops teams",
    ],
    deliveryTime: "7 days",
    icon: "🏛️",
  },
  {
    id: 41,
    name: "Enterprise Marketing Infrastructure",
    category: "Enterprise",
    price: 249999,
    description:
      "Build the complete marketing tech stack that powers 8-figure revenue without human bottlenecks.",
    features: [
      "Martech stack audit and full technology roadmap",
      "Multi-channel campaign orchestration platform setup",
      "Enterprise-level data warehouse and BI integration (BigQuery/Tableau)",
      "Full marketing automation across email, SMS, WhatsApp, and ads",
      "Dedicated marketing operations manager for 90 days post-launch",
      "Quarterly strategy reviews with C-level stakeholders",
    ],
    deliveryTime: "7 days",
    icon: "🏗️",
  },
  {
    id: 42,
    name: "Revenue Operations (RevOps) Build",
    category: "Enterprise",
    price: 99999,
    description:
      "Align sales, marketing, and customer success into one unified revenue machine.",
    features: [
      "RevOps framework design: alignment workshops with all three teams",
      "Unified customer data platform (CDP) setup and integration",
      "Lead lifecycle mapping from first touch to upsell",
      "SLA agreements between marketing, sales, and CS defined and automated",
      "Revenue operations playbook (50+ pages) for ongoing management",
    ],
    deliveryTime: "7 days",
    icon: "⚡",
  },

  // ── GRAPHIC DESIGN (6) ───────────────────────────────────
  {
    id: 43,
    name: "Logo Design",
    category: "Graphic Design",
    price: 2499,
    description:
      "Professional logo with 3 concept options, unlimited revisions, and all file formats included.",
    features: [
      "3 unique logo concepts by senior designers",
      "Unlimited revision rounds until 100% satisfied",
      "Delivery in all formats: PNG, SVG, PDF, EPS, AI",
      "Light and dark version, plus icon-only variant",
      "Brand color palette and font recommendation included",
    ],
    deliveryTime: "5–7 days",
    icon: "✏️",
  },
  {
    id: 44,
    name: "Social Media Graphics Pack",
    category: "Graphic Design",
    price: 4999,
    description:
      "30 branded social media post templates you can edit forever in Canva or Figma.",
    features: [
      "30 editable templates: quote posts, carousels, stories, and reels covers",
      "Consistent brand identity: colors, fonts, and layout system",
      "6 different content categories represented",
      "Canva or Figma file delivered with team sharing access",
      "5 ready-to-post designs created using the templates",
    ],
    deliveryTime: "5–7 days",
    icon: "🖼️",
  },
  {
    id: 45,
    name: "Sales Presentation Design",
    category: "Graphic Design",
    price: 9999,
    description:
      "Investor-grade pitch deck or sales deck that commands attention and closes deals.",
    features: [
      "20-slide custom pitch or sales deck design",
      "Data visualisation: charts, graphs, and infographics",
      "Compelling visual storytelling and hierarchy",
      "PowerPoint, Google Slides, and PDF formats delivered",
      "Speaker notes and delivery coaching tips included",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 46,
    name: "Infographic Design",
    category: "Graphic Design",
    price: 6499,
    description:
      "Shareable, SEO-friendly infographic that earns backlinks and drives organic traffic.",
    features: [
      "2 custom infographic designs on your topic of choice",
      "Research-backed data sourcing and fact verification",
      "Long-form format optimised for Pinterest and blog embedding",
      "Vertical and horizontal layout versions for versatile use",
      "Social media teaser versions for LinkedIn and Instagram",
    ],
    deliveryTime: "5–7 days",
    icon: "📊",
  },
  {
    id: 47,
    name: "Brand Collateral Pack",
    category: "Graphic Design",
    price: 12499,
    description:
      "Full set of on-brand marketing materials: brochures, flyers, business cards, and email signatures.",
    features: [
      "Tri-fold brochure design (front and back, print-ready)",
      "A4 and A5 flyer designs (2 versions each)",
      "Business card design (double-sided, print-ready file)",
      "Email signature design for all team members",
      "Editable master files in Canva or Illustrator",
    ],
    deliveryTime: "5–7 days",
    icon: "📦",
  },
  {
    id: 48,
    name: "UI/UX Design for Mobile App",
    category: "Graphic Design",
    price: 39999,
    description:
      "Full mobile app UI/UX design with interactive Figma prototype ready for developer handoff.",
    features: [
      "User research, persona development, and user flow mapping",
      "Wireframes for all core screens (up to 25 screens)",
      "High-fidelity UI design with custom illustration elements",
      "Interactive Figma prototype with navigation and micro-interactions",
      "Design system: components, tokens, and style guide documentation",
      "Developer handoff file with annotations and asset exports",
    ],
    deliveryTime: "6–7 days",
    icon: "📱",
  },

  // ── LEAD GENERATION (3) ───────────────────────────────────
  {
    id: 49,
    name: "LinkedIn Lead Generation Campaign",
    category: "Lead Generation",
    price: 17499,
    description:
      "Managed LinkedIn outreach campaign generating 30–50 qualified B2B conversations per month.",
    features: [
      "ICP (ideal client profile) definition and target account list building",
      "LinkedIn profile optimisation for credibility and conversion",
      "Personalised connection request + follow-up message sequences",
      "Sales Navigator prospecting and list segmentation",
      "Monthly lead pipeline report with contact database delivery",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 50,
    name: "Lead Magnet Funnel Build",
    category: "Lead Generation",
    price: 22499,
    description:
      "High-converting lead magnet funnel that generates 100+ qualified leads per month on autopilot.",
    features: [
      "Lead magnet creation (checklist, guide, or mini-course)",
      "Opt-in landing page design and copywriting (CRO-optimised)",
      "Thank-you page with tripwire offer for immediate monetization",
      "Email nurture sequence (7 emails) to convert leads to clients",
      "Facebook/Google ad creative to drive traffic to the funnel",
      "Weekly lead count and funnel conversion report",
    ],
    deliveryTime: "5–7 days",
    icon: "🎯",
  },
  {
    id: 51,
    name: "B2B Appointment Setting Service",
    category: "Lead Generation",
    price: 34999,
    description:
      "Dedicated SDR-driven outbound campaign booking qualified discovery calls directly on your calendar.",
    features: [
      "Dedicated SDR managing outreach across email, LinkedIn, and phone",
      "500 personalised outreach touches per month",
      "Guaranteed minimum 8–12 qualified appointments per month",
      "CRM pipeline updates with detailed prospect notes",
      "Weekly performance report and strategy iteration",
    ],
    deliveryTime: "5–7 days",
    icon: "📅",
  },

  // ── PAID ADS (9) ──────────────────────────────────────────
  {
    id: 52,
    name: "Meta Ads Campaign Setup",
    category: "Paid Ads",
    price: 12499,
    description:
      "Full Meta (Facebook + Instagram) ad campaign built, launched, and optimised for maximum ROI.",
    features: [
      "Campaign architecture: awareness, consideration, and conversion campaigns",
      "5 ad creative concepts (static, carousel, and video formats)",
      "Custom audience and lookalike audience setup",
      "Facebook Pixel + CAPI server-side tracking implementation",
      "A/B testing framework for creatives, copy, and audiences",
      "Bi-weekly performance report with optimisation recommendations",
    ],
    deliveryTime: "5–7 days",
    icon: "📘",
  },
  {
    id: 53,
    name: "Google Search Ads Management",
    category: "Paid Ads",
    price: 14999,
    description:
      "Profitable Google Search campaigns targeting buyers with purchase intent.",
    features: [
      "Keyword research and negative keyword library build",
      "Single keyword ad group (SKAG) structure for Quality Score maximisation",
      "10 RSA (responsive search ad) copy variants per campaign",
      "Bidding strategy optimisation: manual CPC, tROAS, tCPA",
      "Monthly search term analysis and bid adjustment report",
    ],
    deliveryTime: "5–7 days",
    icon: "🔍",
  },
  {
    id: 54,
    name: "Google Shopping & Performance Max",
    category: "Paid Ads",
    price: 17499,
    description:
      "Full Google Shopping and Performance Max setup for eCommerce brands to scale ROAS.",
    features: [
      "Google Merchant Center setup and product feed optimisation",
      "Standard Shopping and Performance Max campaign architecture",
      "Product title and description optimisation for CTR",
      "Smart bidding with target ROAS configuration",
      "Weekly ROAS and product-level performance report",
    ],
    deliveryTime: "5–7 days",
    icon: "🛍️",
  },
  {
    id: 55,
    name: "YouTube Ads Campaign",
    category: "Paid Ads",
    price: 19999,
    description:
      "YouTube TrueView and non-skippable ad campaigns to build brand authority and drive conversions.",
    features: [
      "Campaign strategy: awareness, remarketing, and direct response",
      "Video ad creative briefing and storyboard for production team",
      "Custom intent audience targeting using search history data",
      "YouTube remarketing pixel and custom audience list setup",
      "View rate, CTR, and conversion analysis with weekly optimisation",
    ],
    deliveryTime: "5–7 days",
    icon: "▶️",
  },
  {
    id: 56,
    name: "Retargeting Campaign Setup",
    category: "Paid Ads",
    price: 9999,
    description:
      "Cross-platform retargeting campaigns that convert warm audiences who already know your brand.",
    features: [
      "Retargeting audience segmentation by visit depth and behaviour",
      "Meta, Google Display, and YouTube retargeting campaigns",
      "Sequential retargeting messaging strategy (touch 1 → touch 5)",
      "Dynamic retargeting for eCommerce product catalogue",
      "Frequency cap management to prevent ad fatigue",
    ],
    deliveryTime: "5–7 days",
    icon: "🎯",
  },
  {
    id: 57,
    name: "LinkedIn Ads Management",
    category: "Paid Ads",
    price: 22499,
    description:
      "B2B LinkedIn Ads targeting decision-makers by job title, company size, and industry.",
    features: [
      "Campaign objective selection: lead gen forms, website visits, or brand awareness",
      "Audience targeting by seniority, function, company size, and industry",
      "Sponsored content, Message Ads, and Conversation Ads creation",
      "Lead Gen Form setup with CRM integration",
      "Monthly LinkedIn Ads performance audit with budget reallocation",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 58,
    name: "Display & Programmatic Ads",
    category: "Paid Ads",
    price: 24999,
    description:
      "Google Display and programmatic advertising for brand awareness and remarketing at scale.",
    features: [
      "Banner ad creative in all Google Display sizes (15 variants)",
      "Audience targeting: contextual, in-market, and custom intent",
      "Placement exclusion list to protect brand safety",
      "Programmatic DSP campaign setup (DV360 or The Trade Desk)",
      "Viewability and brand lift measurement reporting",
    ],
    deliveryTime: "5–7 days",
    icon: "📺",
  },
  {
    id: 59,
    name: "Ad Creative Production",
    category: "Paid Ads",
    price: 17499,
    description:
      "10 conversion-engineered static and motion ad creatives for Meta, Google, and YouTube.",
    features: [
      "10 ad creatives: 5 static (single image) + 3 carousels + 2 short video ads",
      "Hook-first copywriting for every ad (3 headline variants each)",
      "On-brand design using your visual identity guidelines",
      "Platform-specific size formatting: square, story, banner",
      "Creative performance brief with hypothesis for testing",
    ],
    deliveryTime: "5–7 days",
    icon: "🎨",
  },
  {
    id: 60,
    name: "Paid Ads Full Account Audit",
    category: "Paid Ads",
    price: 74999,
    description:
      "Deep-dive audit of all paid ad accounts with a 90-day scaling roadmap and waste elimination plan.",
    features: [
      "Full account audit: Meta, Google, YouTube, LinkedIn, and Bing",
      "Budget waste identification and savings quantification",
      "Quality Score and Relevance Score improvement recommendations",
      "Creative fatigue analysis and refresh strategy",
      "Landing page CRO recommendations per campaign",
      "90-day paid media scaling roadmap with projected ROAS targets",
    ],
    deliveryTime: "5–7 days",
    icon: "🔬",
  },

  // ── PREMIUM & SCALE (4) ───────────────────────────────────
  {
    id: 61,
    name: "Growth Hacking Sprint",
    category: "Premium & Scale",
    price: 99999,
    description:
      "Intensive 30-day growth sprint applying 20+ rapid experiments to find your fastest growth channels.",
    features: [
      "30-day intensive growth programme with daily optimisation",
      "20 rapid experiments across acquisition, activation, and retention",
      "Validated growth playbook with the top 5 scalable channels",
      "Custom analytics stack to measure each experiment in real time",
      "Weekly growth board presentation to leadership team",
      "Post-sprint scale plan with resource and budget recommendations",
    ],
    deliveryTime: "7 days",
    icon: "🚀",
  },
  {
    id: 62,
    name: "Fractional CMO Service",
    category: "Premium & Scale",
    price: 74999,
    description:
      "Senior CMO-level marketing leadership embedded in your team for 10 hours/week.",
    features: [
      "10 hours/week of senior marketing strategy and execution",
      "Full marketing team management and performance reviews",
      "Board-level marketing reporting and stakeholder communication",
      "Agency and vendor management on your behalf",
      "Hiring and team structure recommendations",
    ],
    deliveryTime: "5–7 days",
    icon: "👑",
  },
  {
    id: 63,
    name: "Scale-Up Revenue Accelerator",
    category: "Premium & Scale",
    price: 199999,
    description:
      "3-month done-with-you programme combining strategy, execution, and coaching to hit 3x revenue.",
    features: [
      "Full business and marketing audit in week one",
      "12 bi-weekly 2-hour coaching and strategy sessions",
      "Done-for-you implementation of top 3 growth initiatives",
      "Full-funnel paid advertising management (up to ₹10L/month budget)",
      "Weekly accountability calls and daily Slack access",
      "Performance guarantee: 2x ROI or money-back",
    ],
    deliveryTime: "7 days",
    icon: "💎",
  },
  {
    id: 64,
    name: "Market Domination Package",
    category: "Premium & Scale",
    price: 149999,
    description:
      "6-month multi-channel market domination: SEO, paid, content, PR, and conversion at full speed.",
    features: [
      "6-month rolling strategy: SEO, PPC, content, social, and email",
      "Dedicated account team of 4: strategist, paid media, SEO, and content specialist",
      "PR outreach and media placement in 5+ industry publications",
      "Competitor monitoring and counter-strategy monthly",
      "Quarterly strategy pivots based on performance data",
      "Monthly executive revenue report with YoY comparison",
    ],
    deliveryTime: "7 days",
    icon: "🌟",
  },

  // ── REPUTATION MANAGEMENT (2) ─────────────────────────────
  {
    id: 65,
    name: "Online Reputation Audit & Repair",
    category: "Reputation Management",
    price: 14999,
    description:
      "Audit and neutralise negative online content while building a positive brand narrative.",
    features: [
      "Comprehensive reputation audit across Google, Yelp, Glassdoor, and social",
      "Negative review response templates and escalation strategy",
      "Positive content creation to outrank negative results on Google",
      "Review generation campaign to increase star ratings on key platforms",
      "Google Business Profile optimisation and management",
    ],
    deliveryTime: "5–7 days",
    icon: "🛡️",
  },
  {
    id: 66,
    name: "Ongoing Reputation Management",
    category: "Reputation Management",
    price: 39999,
    description:
      "Monthly brand monitoring, review management, and positive PR to protect your online image.",
    features: [
      "24/7 brand mention monitoring across 100+ platforms",
      "Monthly review response management (all platforms)",
      "Proactive content publishing to build positive search results",
      "Crisis communication plan and real-time response protocol",
      "Monthly reputation health score report with trend analysis",
    ],
    deliveryTime: "5–7 days",
    icon: "👁️",
  },

  // ── SEO (8) ──────────────────────────────────────────────
  {
    id: 67,
    name: "Technical SEO Audit",
    category: "SEO",
    price: 3999,
    description:
      "Full technical SEO audit covering 150+ factors with a prioritised fix list for maximum ranking impact.",
    features: [
      "Crawl analysis using Screaming Frog: indexability, redirect chains, and errors",
      "Core Web Vitals (LCP, CLS, FID) audit with developer-ready fixes",
      "Site architecture, internal linking, and XML sitemap review",
      "Mobile usability and structured data validation",
      "Prioritised fix list: high/medium/low impact with effort estimates",
    ],
    deliveryTime: "5–7 days",
    icon: "🔧",
  },
  {
    id: 68,
    name: "Keyword Research & Strategy",
    category: "SEO",
    price: 6499,
    description:
      "Data-driven keyword strategy covering 500+ keywords with search intent and opportunity scoring.",
    features: [
      "500+ keyword list segmented by intent: informational, commercial, transactional",
      "Keyword gap analysis vs. your top 5 competitors",
      "Opportunity scoring: volume × difficulty × intent value formula",
      "Topic cluster mapping aligned to your services and products",
      "Keyword tracking setup in SEMrush or Ahrefs dashboard",
    ],
    deliveryTime: "5–7 days",
    icon: "🔑",
  },
  {
    id: 69,
    name: "On-Page SEO Optimisation",
    category: "SEO",
    price: 12499,
    description:
      "Full on-page optimisation for 20 key pages to dramatically improve rankings and organic traffic.",
    features: [
      "Title tag and meta description rewrite for 20 pages",
      "Header hierarchy (H1–H4) restructuring for keyword prominence",
      "Content optimisation using Surfer SEO or Clearscope recommendations",
      "Internal linking audit and strategic link addition",
      "Image ALT text, file name, and compression optimisation",
    ],
    deliveryTime: "5–7 days",
    icon: "📝",
  },
  {
    id: 70,
    name: "Local SEO Setup",
    category: "SEO",
    price: 7499,
    description:
      "Dominate local search results and Google Maps for your target city and service area.",
    features: [
      "Google Business Profile complete setup and optimisation",
      "Local citation building on 50+ directories (NAP consistency)",
      "Local keyword integration: city + service combinations",
      "Review generation strategy and response templates",
      "Local schema markup implementation for rich results",
    ],
    deliveryTime: "5–7 days",
    icon: "📍",
  },
  {
    id: 71,
    name: "Link Building Campaign",
    category: "SEO",
    price: 14999,
    description:
      "High-quality white-hat backlink acquisition to boost domain authority and search rankings.",
    features: [
      "10 high-DA (40+) backlinks acquired per month via outreach",
      "Guest post placements on relevant niche websites",
      "Broken link building and resource page outreach",
      "Anchor text strategy aligned to target keyword rankings",
      "Monthly backlink acquisition report with DA metrics",
    ],
    deliveryTime: "5–7 days",
    icon: "🔗",
  },
  {
    id: 72,
    name: "eCommerce SEO Package",
    category: "SEO",
    price: 19999,
    description:
      "Full eCommerce SEO: category pages, product pages, and structured data for maximum organic revenue.",
    features: [
      "Category and sub-category page SEO optimisation (up to 20 pages)",
      "Product page title, description, and content optimisation (50 products)",
      "Product schema markup: price, availability, reviews structured data",
      "Faceted navigation and pagination SEO configuration",
      "Organic revenue tracking and eCommerce-specific KPI dashboard",
    ],
    deliveryTime: "6–7 days",
    icon: "🛒",
  },
  {
    id: 73,
    name: "SEO Content Writing (Monthly)",
    category: "SEO",
    price: 9999,
    description:
      "4 SEO-optimised blog articles per month written and published to drive consistent organic traffic.",
    features: [
      "4 long-form articles (1,500–2,500 words) per month",
      "Full Surfer SEO / Clearscope content scoring above 75",
      "Primary + secondary keyword integration without stuffing",
      "Custom featured image and SEO-optimised image ALT text",
      "Internal links to 3+ existing pages per article",
    ],
    deliveryTime: "5–7 days",
    icon: "✍️",
  },
  {
    id: 74,
    name: "Enterprise SEO Strategy",
    category: "SEO",
    price: 39999,
    description:
      "Comprehensive enterprise SEO programme for large websites (1,000+ pages) competing for national rankings.",
    features: [
      "Enterprise crawl and log file analysis for 1,000+ URL websites",
      "International SEO: hreflang, subdomain, and geo-targeting setup",
      "Programmatic SEO strategy for scalable content at volume",
      "Core Web Vitals engineering support with dev team integration",
      "Monthly enterprise SEO performance report with executive summary",
      "Dedicated senior SEO strategist as your point of contact",
    ],
    deliveryTime: "6–7 days",
    icon: "🏢",
  },

  // ── SOCIAL MEDIA (9) ─────────────────────────────────────
  {
    id: 75,
    name: "Social Media Profile Setup",
    category: "Social Media",
    price: 2499,
    description:
      "Professional setup of all 5 major social media profiles, fully branded and optimised.",
    features: [
      "Instagram, Facebook, LinkedIn, Twitter/X, and YouTube setup",
      "Profile photo, cover images, and bio optimisation for each platform",
      "Brand consistency check across all platforms",
      "Keyword-rich bio and about sections for discoverability",
      "Pinned post and highlight creation on Instagram",
    ],
    deliveryTime: "3–5 days",
    icon: "📱",
  },
  {
    id: 76,
    name: "Social Media Content Calendar",
    category: "Social Media",
    price: 4999,
    description:
      "30-day content calendar with post ideas, captions, and hashtag sets ready to execute.",
    features: [
      "30 post ideas across 6 content pillars with full caption drafts",
      "Platform-specific formatting: Instagram reels, LinkedIn articles, tweets",
      "Hashtag research: 3 sets of 30 hashtags per content pillar",
      "Best time-to-post schedule based on audience analytics",
      "Content calendar in Notion or Trello with drag-and-drop scheduling",
    ],
    deliveryTime: "5–7 days",
    icon: "📅",
  },
  {
    id: 77,
    name: "Instagram Growth Management",
    category: "Social Media",
    price: 9999,
    description:
      "Full Instagram management: 3x weekly posts, reels strategy, and audience growth.",
    features: [
      "3x weekly posts with captions, hashtags, and graphic design included",
      "2x weekly Reels (short script + design direction guidance)",
      "Daily story posting and poll/quiz engagement tactics",
      "Community management: replies to all comments and DMs within 2 hours",
      "Monthly growth report with follower, reach, and engagement metrics",
    ],
    deliveryTime: "5–7 days",
    icon: "📸",
  },
  {
    id: 78,
    name: "LinkedIn Company Page Management",
    category: "Social Media",
    price: 12499,
    description:
      "Thought leadership content strategy and posting to grow your LinkedIn company following.",
    features: [
      "4x weekly posts: articles, carousels, polls, and company updates",
      "CEO / founder personal branding content strategy included",
      "LinkedIn newsletter setup and bi-monthly edition written",
      "Employee advocacy programme to amplify reach organically",
      "Monthly LinkedIn analytics report: impressions, clicks, and follower growth",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 79,
    name: "YouTube Channel Management",
    category: "Social Media",
    price: 19999,
    description:
      "Full YouTube channel management: strategy, SEO, thumbnails, and community growth.",
    features: [
      "Channel SEO optimisation: description, tags, and keyword placement",
      "Video SEO for each upload: title, description, chapters, and cards",
      "Custom thumbnail design for every video (brand-consistent)",
      "Comment moderation and community tab posts",
      "Monthly channel analytics report with watch time and subscriber metrics",
    ],
    deliveryTime: "5–7 days",
    icon: "▶️",
  },
  {
    id: 80,
    name: "Social Media Advertising (Meta)",
    category: "Social Media",
    price: 14999,
    description:
      "Results-driven Meta social ad management to grow followers, leads, and sales.",
    features: [
      "Campaign objective selection: reach, engagement, or lead generation",
      "5 ad creative and copy variants per campaign",
      "Audience segmentation: interest, behaviour, and lookalike targeting",
      "Daily budget monitoring and bid optimisation",
      "Bi-weekly performance report with ROAS and CPL analysis",
    ],
    deliveryTime: "5–7 days",
    icon: "📢",
  },
  {
    id: 81,
    name: "Influencer Marketing Campaign",
    category: "Social Media",
    price: 24999,
    description:
      "End-to-end influencer campaign from shortlisting to payment and performance reporting.",
    features: [
      "Influencer research and vetting: reach, engagement, and audience fit",
      "Outreach, negotiation, and contract management for 5 influencers",
      "Creative brief and campaign guidelines for brand-safe content",
      "Content review and approval workflow",
      "Post-campaign performance report: reach, impressions, and conversions",
    ],
    deliveryTime: "6–7 days",
    icon: "⭐",
  },
  {
    id: 82,
    name: "Short-Form Video Content Package",
    category: "Social Media",
    price: 17499,
    description:
      "8 scroll-stopping Reels, Shorts, or TikTok scripts and content directions per month.",
    features: [
      "8 video scripts (30–90 seconds) with hook, value, and CTA",
      "On-camera coaching brief for each video",
      "B-roll and graphics direction notes for editing team",
      "Caption and hashtag package for each post",
      "Monthly performance analysis and trend integration",
    ],
    deliveryTime: "5–7 days",
    icon: "🎥",
  },
  {
    id: 83,
    name: "Social Media Full Management Package",
    category: "Social Media",
    price: 49999,
    description:
      "Complete social media management across Instagram, LinkedIn, Facebook, and YouTube.",
    features: [
      "5x weekly posts across all 4 platforms (20 posts/month total)",
      "Full graphic design and content production included",
      "Community management: comments and DMs across all platforms",
      "Monthly paid social budget management (up to ₹1L)",
      "Monthly social media performance report and strategy review",
      "Quarterly brand audit and content strategy refresh",
    ],
    deliveryTime: "5–7 days",
    icon: "🌐",
  },

  // ── STUDENT (5) ──────────────────────────────────────────
  {
    id: 84,
    name: "Digital Marketing Starter Kit",
    category: "Student",
    price: 999,
    description:
      "Beginner-friendly digital marketing setup for students starting their online brand journey.",
    features: [
      "1x social media profile setup and bio optimisation",
      "10 branded Canva post templates in your niche",
      "Starter content calendar (15 post ideas with captions)",
      "Free tools guide: Canva, Google Analytics, and Mailchimp setup",
      "1-hour live onboarding call with a marketing mentor",
    ],
    deliveryTime: "3–5 days",
    icon: "🎓",
  },
  {
    id: 85,
    name: "Student Portfolio Website",
    category: "Student",
    price: 2499,
    description:
      "Professional personal portfolio website to showcase your skills and land internships or jobs.",
    features: [
      "5-page portfolio site: home, about, projects, skills, and contact",
      "Mobile-responsive design with modern layout",
      "Blog/project showcase section for ongoing work",
      "Contact form with email notification",
      "1-month free hosting setup guidance and domain recommendation",
    ],
    deliveryTime: "5–7 days",
    icon: "🌐",
  },
  {
    id: 86,
    name: "Personal Brand Starter Pack",
    category: "Student",
    price: 3499,
    description:
      "Build your personal brand on LinkedIn and Instagram to stand out in your field from day one.",
    features: [
      "LinkedIn profile complete makeover: headline, summary, and skills",
      "Instagram bio and content strategy for your niche",
      "30-day content plan with 30 post ideas and ready captions",
      "Personal logo and profile picture branding treatment",
      "2-hour workshop on building authority as a student creator",
    ],
    deliveryTime: "5–7 days",
    icon: "✨",
  },
  {
    id: 87,
    name: "Freelancing Launch Masterclass",
    category: "Student",
    price: 3999,
    description:
      "Live online programme teaching students how to land their first ₹20,000/month freelance clients.",
    features: [
      "3x live sessions (2 hours each) via Zoom",
      "Niche selection and service positioning framework",
      "Cold outreach playbook: email, LinkedIn, and WhatsApp scripts",
      "Freelance pricing guide and proposal template library",
      "Lifetime community access for peer support and referrals",
    ],
    deliveryTime: "5–7 days",
    icon: "💡",
  },
  {
    id: 88,
    name: "Internship Prep & Resume Kit",
    category: "Student",
    price: 4999,
    description:
      "Resume, cover letter, and interview prep kit crafted for digital marketing internships.",
    features: [
      "ATS-optimised resume redesign for digital marketing roles",
      "Custom cover letter template with personalisation instructions",
      "LinkedIn profile optimisation for recruiter visibility",
      "50 top digital marketing interview Q&A preparation guide",
      "1-hour mock interview session with feedback report",
    ],
    deliveryTime: "5–7 days",
    icon: "📋",
  },

  // ── VIDEO PRODUCTION (3) ─────────────────────────────────
  {
    id: 89,
    name: "Brand Video Production",
    category: "Video Production",
    price: 24999,
    description:
      "2-minute brand story video that communicates your value proposition and builds instant trust.",
    features: [
      "Pre-production: concept development, storyboard, and script",
      "1-day professional shoot with lighting and audio setup",
      "Post-production: colour grading, motion graphics, and music",
      "3 cut lengths: 2-min full version, 60-sec and 30-sec social cuts",
      "3 rounds of revision included",
    ],
    deliveryTime: "6–7 days",
    icon: "🎬",
  },
  {
    id: 90,
    name: "Explainer Video (Animated)",
    category: "Video Production",
    price: 34999,
    description:
      "90-second animated explainer video with professional voiceover and brand-aligned visuals.",
    features: [
      "Script writing and storyboard approval before production starts",
      "Custom 2D/motion graphic animation in brand style",
      "Professional voiceover in English or regional language",
      "Licensed background music and sound effects",
      "MP4 and WebM delivery formats for all platforms",
    ],
    deliveryTime: "6–7 days",
    icon: "🎥",
  },
  {
    id: 91,
    name: "Video Ad Production for Paid Campaigns",
    category: "Video Production",
    price: 49999,
    description:
      "High-converting video ads engineered for Meta, YouTube, and OTT platforms at scale.",
    features: [
      "4 video ad concepts developed from consumer insight research",
      "15-sec, 30-sec, and 60-sec versions for each concept",
      "Hook testing framework: 3 different opening hooks per video",
      "On-screen text, captions, and CTA overlays for all creatives",
      "Platform-specific aspect ratio export: 1:1, 4:5, 9:16, 16:9",
      "Post-launch performance brief for creative iteration",
    ],
    deliveryTime: "7 days",
    icon: "📹",
  },

  // ── WEB DEVELOPMENT (6) ─────────────────────────────────
  {
    id: 92,
    name: "Landing Page Design & Development",
    category: "Web Development",
    price: 12499,
    description:
      "High-converting, mobile-first landing page built to generate leads or sales from day one.",
    features: [
      "Custom design based on your brand (no templates)",
      "Conversion-optimised layout: headline, social proof, and CTA hierarchy",
      "Lead capture form or checkout integration",
      "Page speed optimisation: 90+ Google PageSpeed score",
      "A/B testing setup for headline and CTA variants",
    ],
    deliveryTime: "5–7 days",
    icon: "🎯",
  },
  {
    id: 93,
    name: "Business Website (10 Pages)",
    category: "Web Development",
    price: 39999,
    description:
      "Professional, fast, and SEO-ready 10-page business website built on WordPress or Next.js.",
    features: [
      "10 custom-designed pages: home, about, services, blog, contact, and more",
      "Mobile-first responsive design with smooth scroll animations",
      "CMS integration for easy content updates without developer help",
      "SEO foundation: schema markup, sitemap, and meta tags",
      "Contact and inquiry forms with CRM integration",
      "30-day post-launch support and bug fixes",
    ],
    deliveryTime: "6–7 days",
    icon: "🌐",
  },
  {
    id: 94,
    name: "eCommerce Website Build",
    category: "Web Development",
    price: 74999,
    description:
      "Full-featured Shopify or WooCommerce store with product catalogue, checkout, and payment gateway.",
    features: [
      "Shopify or WooCommerce store setup and theme customisation",
      "Up to 100 products uploaded with descriptions and images",
      "Razorpay / Stripe payment gateway integration",
      "Abandoned cart recovery and email automation setup",
      "Speed optimisation and mobile UX refinement",
      "3-month post-launch growth consultation included",
    ],
    deliveryTime: "7 days",
    icon: "🛒",
  },
  {
    id: 95,
    name: "SaaS Web Application Development",
    category: "Web Development",
    price: 149999,
    description:
      "MVP-level SaaS application with user auth, dashboard, and core feature set ready to launch.",
    features: [
      "Product scope workshop and feature prioritisation (MoSCoW method)",
      "UI/UX design in Figma with interactive prototype",
      "Full-stack development: React + Node.js / Next.js",
      "User authentication, roles, and permissions system",
      "Payment subscription integration (Stripe / Razorpay)",
      "Cloud deployment (AWS / GCP) with CI/CD pipeline setup",
    ],
    deliveryTime: "7 days",
    icon: "💻",
  },
  {
    id: 96,
    name: "Website Speed & Performance Optimisation",
    category: "Web Development",
    price: 9999,
    description:
      "Get your site to 90+ Google PageSpeed and Core Web Vitals to rank higher and convert more.",
    features: [
      "Full Core Web Vitals audit: LCP, CLS, and FID diagnosis",
      "Image compression, lazy loading, and next-gen format (WebP) conversion",
      "JavaScript and CSS minification and critical CSS extraction",
      "CDN integration (Cloudflare or CloudFront) setup",
      "Before-and-after PageSpeed score report with improvement summary",
    ],
    deliveryTime: "5–7 days",
    icon: "⚡",
  },
  {
    id: 97,
    name: "Website Maintenance & Support Plan",
    category: "Web Development",
    price: 7499,
    description:
      "Monthly website maintenance: updates, backups, security monitoring, and unlimited small edits.",
    features: [
      "Weekly WordPress / plugin / theme security updates",
      "Daily automated backups with 30-day retention",
      "Security monitoring and malware scan with incident response",
      "Up to 3 hours of content edits or small feature additions per month",
      "Monthly website health report with uptime statistics",
    ],
    deliveryTime: "3–5 days",
    icon: "🔒",
  },

  // ── WEBSITE DESIGN & DEVELOPMENT — BUSINESS (14) ────────
  {
    id: 99,
    name: "Startup Business Website",
    category: "Website Design & Development",
    price: 4999,
    description:
      "Clean, modern 5-page website for early-stage startups to establish credibility and attract investors or customers.",
    features: [
      "5 custom-designed pages: Home, About, Services, Team, and Contact",
      "Mobile-first responsive design with smooth CSS animations",
      "Brand color integration and professional typography system",
      "Contact & inquiry form with email notification setup",
      "Basic SEO: meta tags, page titles, and sitemap submission",
      "Google Analytics integration for visitor tracking",
      "30-day post-launch support and minor content tweaks included",
    ],
    deliveryTime: "5–7 days",
    icon: "🚀",
  },
  {
    id: 100,
    name: "Corporate Company Website",
    category: "Website Design & Development",
    price: 9999,
    description:
      "Professional 8-page corporate website that builds authority, showcases your team, and drives enterprise enquiries.",
    features: [
      "8 pages: Home, About, Services, Team, Clients, Blog, Careers, and Contact",
      "Premium layout with parallax scrolling and section transitions",
      "Team profiles with photos, designations, and LinkedIn links",
      "Client logos / testimonials section with slider",
      "Blog/news CMS integration for self-managed content publishing",
      "Lead inquiry form with CRM-ready webhook integration",
      "Core Web Vitals optimised — 85+ PageSpeed score guaranteed",
    ],
    deliveryTime: "5–7 days",
    icon: "🏢",
  },
  {
    id: 101,
    name: "SME Business Website",
    category: "Website Design & Development",
    price: 3999,
    description:
      "Affordable yet professional 5-page website for small and medium enterprises to generate local leads online.",
    features: [
      "5-page clean layout: Home, About, Services, Gallery, and Contact",
      "WhatsApp click-to-chat button integration for instant enquiries",
      "Google Maps embed with business location and directions",
      "Basic image gallery showcasing your work or products",
      "Mobile-optimised design tested across 6 device sizes",
      "Free SSL setup and domain configuration guidance",
    ],
    deliveryTime: "5–7 days",
    icon: "🏪",
  },
  {
    id: 102,
    name: "Restaurant & Food Business Website",
    category: "Website Design & Development",
    price: 6499,
    description:
      "Mouthwatering restaurant website with online menu, reservation form, and food gallery to fill your tables.",
    features: [
      "Stunning food photography-driven homepage layout",
      "Interactive digital menu with categories and price display",
      "Online table reservation form with confirmation email",
      "Chef profile and signature dish showcase section",
      "Location, hours, and Google Maps integration",
      "Social media feeds integration (Instagram food posts)",
      "Zomato / Swiggy / Magicpin quick-link buttons",
    ],
    deliveryTime: "5–7 days",
    icon: "🍽️",
  },
  {
    id: 103,
    name: "Clinic & Healthcare Website",
    category: "Website Design & Development",
    price: 7499,
    description:
      "Trust-building clinic website with doctor profiles, appointment booking, and patient education content.",
    features: [
      "Doctor/specialist profiles with qualifications, experience, and photos",
      "Online appointment booking form with date/time selection",
      "Services and treatments catalogue with detailed descriptions",
      "Patient testimonials and before/after case results section",
      "Health blog CMS for publishing articles and health tips",
      "HIPAA-friendly contact forms with secure data handling",
      "Emergency contact and ambulance hotline button",
    ],
    deliveryTime: "5–7 days",
    icon: "🏥",
  },
  {
    id: 104,
    name: "Real Estate Agency Website",
    category: "Website Design & Development",
    price: 12499,
    description:
      "Property listing website with search filters, virtual tour embeds, and lead capture for real estate agents.",
    features: [
      "Property listing pages with photos, price, size, and amenities",
      "Search and filter by location, price range, BHK, and type",
      "Property enquiry forms with instant WhatsApp notification",
      "Agent/broker profile pages with contact details",
      "Virtual tour / YouTube embed support for 3D walkthroughs",
      "Testimonials and past sales success stories section",
      "Map integration showing nearby schools, hospitals, and transport",
    ],
    deliveryTime: "5–7 days",
    icon: "🏠",
  },
  {
    id: 105,
    name: "Hotel & Hospitality Website",
    category: "Website Design & Development",
    price: 11499,
    description:
      "Luxury hotel website with room gallery, amenities showcase, and direct booking to reduce OTA commissions.",
    features: [
      "Immersive full-screen image/video hero for ambiance impact",
      "Room types catalogue with photos, features, and rates",
      "Online booking enquiry form with availability check",
      "Amenities showcase: pool, spa, restaurant, and events",
      "Guest testimonials and TripAdvisor rating integration",
      "Special offers and seasonal packages highlighted section",
      "Multi-language support (English + regional language option)",
    ],
    deliveryTime: "5–7 days",
    icon: "🏨",
  },
  {
    id: 106,
    name: "NGO & Non-Profit Website",
    category: "Website Design & Development",
    price: 4499,
    description:
      "Impactful NGO website that tells your story, attracts donors, and drives volunteer sign-ups.",
    features: [
      "Mission, vision, and impact metrics prominently showcased",
      "Donation button with Razorpay / UPI payment integration",
      "Volunteer registration and sign-up form",
      "Ongoing projects and completed campaign photo galleries",
      "News and press release CMS for regular updates",
      "Donor wall / recognition section for major contributors",
      "SSL-secured and GDPR-compliant data handling",
    ],
    deliveryTime: "5–7 days",
    icon: "🌱",
  },
  {
    id: 107,
    name: "Education & Coaching Institute Website",
    category: "Website Design & Development",
    price: 8499,
    description:
      "Student-attracting education website with course listings, faculty profiles, and admission inquiry forms.",
    features: [
      "Course catalogue with fees, duration, eligibility, and outcomes",
      "Faculty/trainer profiles with qualifications and experience",
      "Admission enquiry and application form with document upload",
      "Student success stories and placement records showcase",
      "Video testimonials and campus/classroom photo gallery",
      "Upcoming batches and events notice board",
      "Live chat / WhatsApp widget for instant admission queries",
    ],
    deliveryTime: "5–7 days",
    icon: "🎓",
  },
  {
    id: 108,
    name: "Manufacturing & Industrial Website",
    category: "Website Design & Development",
    price: 9499,
    description:
      "B2B manufacturing website showcasing your production capabilities, certifications, and product catalogue.",
    features: [
      "Product catalogue with technical specifications and downloadable PDFs",
      "Manufacturing process and facility photo/video showcase",
      "Quality certifications and compliance badges section",
      "B2B inquiry form with bulk order request fields",
      "Export market information and international trade partnerships",
      "News section for industry updates and company milestones",
      "Multi-currency price display for international buyers",
    ],
    deliveryTime: "5–7 days",
    icon: "⚙️",
  },
  {
    id: 109,
    name: "Law Firm & Legal Services Website",
    category: "Website Design & Development",
    price: 10999,
    description:
      "Professional law firm website that establishes authority, showcases expertise, and generates client consultations.",
    features: [
      "Practice areas pages with detailed legal service descriptions",
      "Attorney / partner profiles with bar credentials and case highlights",
      "Free consultation booking form with preferred date/time",
      "Client testimonials and landmark case victories section",
      "Legal blog CMS for publishing articles and jurisdiction updates",
      "Confidentiality assurance and privacy policy page",
      "Click-to-call button and emergency legal helpline integration",
    ],
    deliveryTime: "5–7 days",
    icon: "⚖️",
  },
  {
    id: 110,
    name: "CA / Finance & Accounting Website",
    category: "Website Design & Development",
    price: 7499,
    description:
      "Trust-centric CA firm website with service listings, client portal info, and appointment booking.",
    features: [
      "Services showcase: auditing, taxation, GST, compliance, and advisory",
      "Partner and team profiles with ICAI credentials",
      "Appointment booking form for consultation scheduling",
      "Client testimonials and industry association memberships",
      "Tax deadline calendar and compliance reminder blog section",
      "Secure document inquiry portal link integration",
      "WhatsApp quick-connect for urgent financial queries",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 111,
    name: "E-Commerce Product Store Website",
    category: "Website Design & Development",
    price: 17499,
    description:
      "Fully functional e-commerce website with product pages, cart, and Razorpay payment gateway for selling online.",
    features: [
      "Up to 50 products with images, descriptions, and variants (size/color)",
      "Shopping cart, wishlist, and secure checkout flow",
      "Razorpay / UPI / COD payment gateway integration",
      "Order confirmation emails and WhatsApp notification setup",
      "Customer account registration and order history section",
      "Coupon / discount code management system",
      "Mobile-first design with 95+ PageSpeed score",
    ],
    deliveryTime: "6–7 days",
    icon: "🛍️",
  },
  {
    id: 112,
    name: "Salon & Beauty Business Website",
    category: "Website Design & Development",
    price: 5999,
    description:
      "Stylish salon website with service menu, before/after gallery, and online appointment booking.",
    features: [
      "Services and pricing menu with categories (hair, skin, nails, etc.)",
      "Before & after transformation photo gallery",
      "Online appointment booking with stylist/therapist selection",
      "Staff profiles and specialisation showcases",
      "Loyalty program and offer highlights section",
      "Instagram feed integration for real-time portfolio updates",
      "WhatsApp booking button for instant appointment confirmations",
    ],
    deliveryTime: "5–7 days",
    icon: "💇",
  },

  // ── WEBSITE DESIGN & DEVELOPMENT — FREELANCING (4) ───────
  {
    id: 113,
    name: "Freelancer Portfolio Website",
    category: "Website Design & Development",
    price: 2499,
    description:
      "Stunning personal portfolio to showcase your work, skills, and attract high-paying freelance clients globally.",
    features: [
      "5-page portfolio: Home, About, Portfolio, Services, and Contact",
      "Project case study pages with problem–solution–results structure",
      "Skills progress bars and technology/tool showcase section",
      "Client testimonials with star ratings and project details",
      "Resume / CV download button with PDF attachment",
      "Contact form with instant email notification",
      "Google Analytics + Clarity heatmap integration",
    ],
    deliveryTime: "5–7 days",
    icon: "🎨",
  },
  {
    id: 114,
    name: "Freelance Service Showcase Website",
    category: "Website Design & Development",
    price: 3499,
    description:
      "Professional service website for freelancers to list their offerings, pricing, and convert visitors to clients.",
    features: [
      "Services section with detailed packages and pricing tables",
      "How It Works step-by-step process section",
      "Portfolio / case studies gallery with project results",
      "Client logos and testimonial slider for social proof",
      "FAQ section addressing common client objections",
      "Lead capture form with project brief intake fields",
      "WhatsApp and Calendly link integration for direct booking",
    ],
    deliveryTime: "5–7 days",
    icon: "💼",
  },
  {
    id: 115,
    name: "Freelance Booking & Consultation Website",
    category: "Website Design & Development",
    price: 4999,
    description:
      "High-converting freelance website with calendar booking, package selection, and payment links to close clients fast.",
    features: [
      "Calendly or Cal.com calendar booking integration",
      "Service packages with tiered pricing (Basic, Standard, Premium)",
      "Instant payment link integration (Razorpay) per package",
      "Testimonials video or written slider with client names and outcomes",
      "Discovery call landing page with qualifying questions form",
      "Automated confirmation email on booking",
      "Mobile-optimised with click-to-call and WhatsApp floating button",
    ],
    deliveryTime: "5–7 days",
    icon: "📅",
  },
  {
    id: 116,
    name: "Freelancer Personal Branding Website",
    category: "Website Design & Development",
    price: 7499,
    description:
      "Authority-building personal brand website for senior freelancers, consultants, and coaches to attract premium clients.",
    features: [
      "Premium hero section with professional headshot and authority tagline",
      "Speaking engagements, podcast appearances, and media mentions section",
      "Thought leadership blog CMS with email subscription pop-up",
      "Signature service or course landing page built in",
      "Video introduction / YouTube embed for instant credibility",
      "Press kit / media page with bio, headshots, and talking points",
      "Email list opt-in with lead magnet PDF delivery automation",
    ],
    deliveryTime: "5–7 days",
    icon: "⭐",
  },

  // ── WEBSITE DESIGN & DEVELOPMENT — PERSONAL (5) ──────────
  {
    id: 117,
    name: "Personal Website",
    category: "Website Design & Development",
    price: 999,
    description:
      "Simple, elegant personal website to introduce yourself online — perfect for professionals and job seekers.",
    features: [
      "3-page site: Home, About Me, and Contact",
      "Clean minimal design with your photo and personal bio",
      "Skills and interests section with clean icon layout",
      "Social media links: LinkedIn, Instagram, Twitter/X, and GitHub",
      "Contact form with email notification",
      "Mobile-responsive design optimised for all screen sizes",
      "Free deployment guidance on GitHub Pages or Netlify",
    ],
    deliveryTime: "2–3 days",
    icon: "👤",
  },
  {
    id: 118,
    name: "Personal Blog Website",
    category: "Website Design & Development",
    price: 2999,
    description:
      "Beautiful blog website where you can write, publish, and grow an audience around your passion or expertise.",
    features: [
      "WordPress CMS setup so you can publish without a developer",
      "Unlimited blog posts with categories, tags, and search",
      "Email newsletter subscribe widget with Mailchimp integration",
      "Comment section with spam protection (Akismet)",
      "Social share buttons on every post for viral reach",
      "Featured article pinning and reading time estimate on posts",
      "SEO-ready with Yoast SEO plugin configured for every post",
    ],
    deliveryTime: "5–7 days",
    icon: "✍️",
  },
  {
    id: 119,
    name: "Digital Resume Website",
    category: "Website Design & Development",
    price: 1499,
    description:
      "Interactive online resume that makes you stand out vs. PDF — ideal for job seekers and fresh graduates.",
    features: [
      "Single-page scrollable resume with all sections beautifully laid out",
      "Work experience timeline with company logos and role details",
      "Education, certifications, and achievements section",
      "Skills grid with proficiency indicators",
      "Downloadable PDF resume button integration",
      "Projects or portfolio mini-gallery with GitHub / live links",
      "Contact form and LinkedIn profile link for recruiter outreach",
    ],
    deliveryTime: "2–3 days",
    icon: "📄",
  },
  {
    id: 120,
    name: "Wedding / Invitation Website",
    category: "Website Design & Development",
    price: 3999,
    description:
      "Romantic, memorable wedding website with RSVP, couple story, event details, and photo gallery.",
    features: [
      "Couple story timeline from first meeting to engagement",
      "Wedding date countdown timer with animated display",
      "Event details for ceremony, reception, and other functions",
      "Google Maps embed for venue with directions and parking info",
      "Online RSVP form with meal preference and guest count",
      "Photo gallery for engagement shoot or pre-wedding photos",
      "Wishes / message wall where guests can leave congratulations",
    ],
    deliveryTime: "3–5 days",
    icon: "💍",
  },
  {
    id: 121,
    name: "Events & Occasion Website",
    category: "Website Design & Development",
    price: 4499,
    description:
      "Custom event website for conferences, concerts, birthdays, or reunions with registration and countdown.",
    features: [
      "Event details page: date, time, venue, schedule, and speakers",
      "Live countdown timer to build anticipation",
      "Event registration form with ticket category selection",
      "Razorpay payment integration for paid ticketed events",
      "Sponsors / partners logo showcase section",
      "Photo gallery from past events or teaser visuals",
      "Social sharing buttons and WhatsApp group invite link",
    ],
    deliveryTime: "3–5 days",
    icon: "🎉",
  },

  // ── WEB3 & BLOCKCHAIN (1) ─────────────────────────────────
  {
    id: 122,
    name: "NFT & Web3 Website Development",
    category: "Web3 & Blockchain",
    price: 149999,
    description:
      "Full Web3 website with wallet connect, NFT minting, and smart contract integration.",
    features: [
      "Custom Web3 website design and development (React + ethers.js)",
      "MetaMask and WalletConnect multi-wallet integration",
      "NFT minting page with smart contract deployment on Ethereum or Polygon",
      "IPFS metadata and image storage setup via Pinata",
      "Whitelist and presale phase management system",
      "Launch strategy consultation and Discord community setup guidance",
    ],
    deliveryTime: "6–7 days",
    icon: "⛓️",
  },
];

// Fix the price for service 9 (Sales Funnel Automation) - was accidentally set to 1
SERVICES_DATA[8].price = 99999;

export const ENTERPRISE_PLANS: EnterprisePlan[] = [
  {
    id: 1,
    name: "Titan",
    price: "₹74,999",
    period: "one-time",
    tagline: "Scale with AI-Powered Systems",
    highlighted: false,
    color: "#00ffc6",
    features: [
      "Full website architecture up to 20 pages with CMS",
      "AI-powered CRM setup & automation for your sales process",
      "Meta & Google Ads management (up to ₹5L/month ad spend)",
      "3x weekly social media posts across Instagram, LinkedIn & Facebook",
      "Email automation sequences — up to 10 active flows",
      "WhatsApp chatbot integration for lead qualification",
      "Basic lead generation funnel with opt-in and thank-you pages",
      "Full on-page & technical SEO for up to 30 pages",
      "Brand identity design — logo, colors, and typography",
      "Monthly performance analytics dashboard with 20+ KPIs",
      "2x monthly strategy calls (1 hour each) with senior strategist",
      "Dedicated account manager as primary point of contact",
      "Business hours chat & email support (Mon–Sat, 9am–7pm)",
      "30-day content calendar planned and designed each month",
      "Competitor intelligence report delivered quarterly",
      "CRM pipeline engineering with deal-stage automation",
    ],
  },
  {
    id: 2,
    name: "Apex",
    price: "₹1,49,999",
    period: "one-time",
    tagline: "Dominate Your Market",
    highlighted: true,
    color: "#ff6a00",
    features: [
      "Enterprise website up to 50 pages with headless CMS and custom integrations",
      "Advanced CRM engineering: HubSpot or Salesforce full configuration",
      "Meta, Google, LinkedIn & YouTube Ads (up to ₹20L/month ad spend)",
      "Daily social media management across 5 platforms with video shorts",
      "Unlimited email automation flows with AI-driven send-time optimisation",
      "AI chatbot on website, WhatsApp, and Instagram DM simultaneously",
      "Full revenue funnel — awareness to upsell with 7-stage automation",
      "Complete SEO programme: technical, on-page, content, and link building",
      "Full brand identity system + quarterly creative refresh",
      "Real-time revenue operations dashboard connected to CRM and ad accounts",
      "4x weekly 1-hour strategy & execution calls with dedicated team",
      "Priority account director and 2-member delivery team assigned",
      "24/7 priority support via WhatsApp and dedicated Slack channel",
      "Video production: 2x brand/explainer videos per quarter",
      "Influencer marketing: 3 campaigns per quarter with 10 influencers each",
      "Quarterly business growth workshop with founder-level strategic review",
    ],
  },
  {
    id: 3,
    name: "Sovereign",
    price: "₹2,99,999",
    period: "one-time",
    tagline: "Total Revenue Supremacy",
    highlighted: false,
    color: "#00ffc6",
    features: [
      "Unlimited page enterprise website with custom web application features",
      "Full RevOps implementation: CRM, ERP, and CDP unification",
      "Unlimited ad spend management across all paid platforms globally",
      "Dedicated social media team (3 specialists) — unlimited content creation",
      "Proprietary AI automation ecosystem custom-built for your business",
      "Custom AI chatbot with NLP and voice assistant capability",
      "Multi-market revenue funnel architecture for international expansion",
      "Enterprise SEO programme with dedicated senior strategist and link building team",
      "Fractional CMO service: 10 hours/week of C-level marketing leadership",
      "White-glove data infrastructure: BigQuery, Tableau, and predictive analytics",
      "Weekly executive strategy sessions + daily on-demand strategy access",
      "Dedicated team of 6: CMO, growth strategist, paid media lead, SEO lead, content director, developer",
      "24/7 emergency support with 30-minute SLA response",
      "Monthly video production: 4 brand films, 8 ad creatives, 16 short-form videos",
      "PR & media placement: 3 tier-1 publications per month guaranteed",
      "Performance guarantee: minimum 3x ROI within 90 days or full refund",
    ],
  },
];

export const CATEGORIES = [
  "All",
  "Analytics",
  "Automation & AI",
  "Business & Agency",
  "Content Marketing",
  "Digital Marketing",
  "Email Marketing",
  "Enterprise",
  "Graphic Design",
  "Lead Generation",
  "Paid Ads",
  "Premium & Scale",
  "Reputation Management",
  "SEO",
  "Social Media",
  "Student",
  "Video Production",
  "Web Development",
  "Web3 & Blockchain",
  "Website Design & Development",
];
